cmake_minimum_required(VERSION 4.1)
project(algorithm_journey)

set(CMAKE_CXX_STANDARD 14)

add_executable(algorithm_journey
        class035/Code01_SetAllHashMap.cpp
        class035/Code02_LRU.cpp
        class035/Code03_InsertDeleteRandom.cpp
        class035/Code04_InsertDeleteRandomDuplicatesAllowed.cpp
        class035/Code05_MedianFinder.cpp
        class035/Code06_MaximumFrequencyStack.cpp
        class035/Code07_AllO1.cpp)
